### PR TITLE
implemented progress bar

### LINKED ISSUE #45: Create progress bar
Since the adoptation of dataframes backtesting takes significantly more time. Therefore, it is nice to add a loading bar to see the the progress.

Things to be done:
* Implement progress bar in backtesting

### PR DESCRIPTION
**Pull request by noudcorten**
# Fixes

Fixes #45 

# What has been changed?

* Adoption of progress bar

# Examples

image

# Actions to be performed before this can be merged

- [requirements.txt] Need to install the tqdm module

# Security Measures

# Potential Issues/Future considerations

# Additional Info

### CODE REVIEW

**Review by dema-trading-ai — APPROVED** [review]
This is very awesome!

**Comment by pvdklei** [comment]
Something weird happens on my computer: the progress bar is shown first, and then all the other `[INFO]`'s come. Not sure why, and I cannot print anything above the progress bar. Even if I print something on the first line in `main()`, the progress bar goes first. 

Screenshot 2021-03-03 at 17 37 18

**Comment by keebrev** [comment]
> Something weird happens on my computer: the progress bar is shown first, and then all the other `[INFO]`'s come. Not sure why, and I cannot print anything above the progress bar. Even if I print something on the first line in `main()`, the progress bar goes first.
> 
> Screenshot 2021-03-03 at 17 37 18

Yes, I am not sure. But I think there's no other option. I think this is fine anyway, since the user now atleast has some indication of how long it's going to take. cc @noudcorten

**Comment by noudcorten** [comment]
> > Something weird happens on my computer: the progress bar is shown first, and then all the other `[INFO]`'s come. Not sure why, and I cannot print anything above the progress bar. Even if I print something on the first line in `main()`, the progress bar goes first.
> > Screenshot 2021-03-03 at 17 37 18
> 
> Yes, I am not sure. But I think there's no other option. I think this is fine anyway, since the user now atleast has some indication of how long it's going to take. cc @noudcorten

@pvdklei Hmm what a weird bug. Can you tell me which OS and python version you are using?

**Comment by pvdklei** [comment]
I'm on MacOS Big Sur (M1 chip, so that could be it), in a zsh shell... But anyway, it still looks very good!!! Let's just merge it and maybe make a new issue out of this one.

**Review by pvdklei — APPROVED** [review]

**Pull request merged**
