### PR TITLE
Added ability to dynamically change the stoploss in a strategy

### LINKED ISSUE #75: Dynamic stoploss for every trade
We have to have to ability to configure stoploss (SL) on a per trade basis. This allows for configuring stoplosses on the go, based on indicators for example. This should be an option for more advanced users. 
The config should have the standard 'static' stoploss, which gets overridden in case a user specifies it when opening a trade. 

Things to do:
- Create method in strategy base class, method should return stoploss (float) for every new trade
- Baseclass method always returns config default SL
- Create SL calculation method in strategy, so it's configurable for every trade that opens + for every strategy
- Call SL calculation method on opening trade. Store SL in trade model
- Add property to trade model for storing trade specific SL
- Adjust methods in trading module for working with trade specific SL when this is turned on

### PR DESCRIPTION
**Pull request by pvdklei**
# Fixes

Fixes #75

# What has been changed?

You now have the option to change the stoploss per every tick by overriding the `stoploss` method on `Strategy`. If not provided, use configured stoploss value. This stoploss is also saved in every trade. 

I also changed some of the variable names and docstrings in `Strategy`. For instance the candle and indicator dataframes were both named `dataframe: DataFrame`. Ambiguous, and the type annotation already stated that is a `DataFrame`. 

# Examples

# Actions to be performed before this can be merged

- [ ] PR depends on #
- [ ] Script to be run

# Security Measures

# Potential Issues/Future considerations

# Additional Info

### CODE REVIEW

**Comment by keebrev** [comment]
Could you make the stoploss method static / abstract? So people can implement this in their own strategy.

**Comment by pvdklei** [comment]
@keebrev they already can, making it an abstract method would obligate users to override it (throw an error if they do not). We want to make it optional right. Static would mean that you cannot take in `self` as a parameter.

**Comment by dema-trading-ai** [comment]
@pvdklei ah alright, then it's perfectly fine.

**Review by dema-trading-ai — APPROVED** [review]

**Review by keebrev — APPROVED** [review]

**Comment by marijn111** [comment]
@pvdklei Does this change the stoploss for all open trades or just for a specific one?

**Pull request merged**
