### PR TITLE
[ENG-54] Remove redundant config classes

### PR DESCRIPTION
**Pull request by sheridavandenbent**
# Results of merging this
Cleans up the code a little bit and removes two redundant classes.

### CODE REVIEW

**Review by WillemGerritzen — CHANGES_REQUESTED** [review]
Made some comments

**Comment by sheridavandenbent** [comment]
Ready for re-review @WillemGerritzen

**Review by WillemGerritzen — DISMISSED** [review]
lgtm

**Review by WillemGerritzen — APPROVED** [review]
lgtm

**Pull request merged**
